name: vear
configs:
  Debug: debug
  Release: release
include:
  - XcodeGen/Versions.yml
  - XcodeGen/Packages.yml
  - XcodeGen/AggregateTargets.yml
  - XcodeGen/TargetTemplates.yml
  - XcodeGen/App.yml
  - XcodeGen/Resource.yml
  - XcodeGen/Entity.yml
  - XcodeGen/Ask.yml
  - XcodeGen/Broadcast.yml
  - XcodeGen/UI.yml
  - XcodeGen/Tracker.yml
  - XcodeGen/Tutorial.yml
  - XcodeGen/VendorFramework.yml